from utils.deepseek_client import ask_deepseek


def compare_tool(vectorstore, chat_history):
    """
    Compare the main topics, methods, and conclusions
    of the uploaded PDFs.

    Parameters:
        vectorstore: FAISS vector database
        chat_history: Current conversation history

    Returns:
        answer: Comparison result generated by DeepSeek
        results: Retrieved document chunks
    """

    # Retrieve representative chunks
    # from multiple documents
    results = vectorstore.similarity_search(
        "compare the uploaded PDFs",
        k=8
    )

    # Comparison instruction
    question = (
        "Compare the uploaded PDFs. "
        "Identify their main topics, similarities, "
        "differences, methods, and conclusions. "
        "Present the comparison clearly."
    )

    # Generate comparison result using DeepSeek
    answer = ask_deepseek(
        question,
        results,
        chat_history
    )

    return answer, results