from utils.deepseek_client import ask_deepseek


def keyword_tool(vectorstore, chat_history):
    """
    Extract important keywords from uploaded PDFs.

    Parameters:
        vectorstore: FAISS vector database
        chat_history: Current conversation history

    Returns:
        answer: Extracted keywords generated by DeepSeek
        results: Retrieved document chunks
    """

    # Retrieve representative chunks
    # for keyword extraction
    results = vectorstore.similarity_search(
        "extract important keywords and key concepts from the PDFs",
        k=5
    )

    # Keyword extraction instruction
    question = (
        "Please extract the most important keywords "
        "and key concepts from the uploaded PDFs. "
        "Return them as a clear bullet list."
    )

    # Generate keywords using DeepSeek
    answer = ask_deepseek(
        question,
        results,
        chat_history
    )

    return answer, results