from utils.deepseek_client import ask_deepseek


def pdf_qa_tool(question, vectorstore, chat_history):
    """
    Answer user questions based on PDF content.

    Parameters:
        question: User's question
        vectorstore: FAISS vector database
        chat_history: Current conversation history

    Returns:
        answer: Answer generated by DeepSeek
        results: Retrieved document chunks
    """

    # Retrieve the most relevant chunks
    # from the vector database
    results = vectorstore.similarity_search(question, k=3)

    # Generate answer using DeepSeek
    answer = ask_deepseek(
        question,
        results,
        chat_history
    )

    return answer, results