from utils.deepseek_client import ask_deepseek


def pdf_summary_tool(vectorstore, chat_history):
    """
    Generate a summary of all uploaded PDFs.

    Parameters:
        vectorstore: FAISS vector database
        chat_history: Current conversation history

    Returns:
        answer: Summary generated by DeepSeek
        results: Retrieved document chunks
    """

    # Retrieve representative chunks
    # for document summarization
    results = vectorstore.similarity_search(
        "summarize the main content of the PDFs",
        k=5
    )

    # Summary instruction
    question = "Please summarize the main content of the uploaded PDFs."

    # Generate summary using DeepSeek
    answer = ask_deepseek(
        question,
        results,
        chat_history
    )

    return answer, results