from utils.deepseek_client import ask_deepseek


def pdf_summary_tool(vectorstore, chat_history):
    """
    Generate a summary of all uploaded PDFs.

    Parameters:
        vectorstore: FAISS vector database
        chat_history: Current conversation history

    Returns:
        answer: Summary generated by DeepSeek
        results: Retrieved document chunks
    """

    # Retrieve more chunks to cover multiple PDFs
    results = vectorstore.similarity_search(
        "document summary main topic overview",
        k=30
    )

    # Keep only a few chunks from each PDF
    grouped_docs = {}
    selected_docs = []

    for doc in results:
        source = doc.metadata.get("source", "Unknown Source")

        if source not in grouped_docs:
            grouped_docs[source] = 0

        if grouped_docs[source] < 3:
            selected_docs.append(doc)
            grouped_docs[source] += 1

    question = (
        "Please summarize EACH uploaded PDF separately. "
        "For each PDF, mention the PDF filename, main topic, "
        "key points, and conclusion. "
        "Then provide a short overall summary."
    )

    answer = ask_deepseek(
        question,
        selected_docs,
        chat_history
    )

    return answer, selected_docs